name: Format

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: generate_token
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.CLIENT_PRIVATE_KEY }}

      - uses: actions/checkout@v7
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install npm dependencies
        shell: bash
        run: |
          nix develop --command npm ci

      - name: Run treefmt and commit changes
        shell: bash
        run: |
          nix develop --command treefmt
          if ! git diff --exit-code; then
            git config user.name "${{ steps.generate_token.outputs.app-slug }}[bot]"
            git config user.email "${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: treefmt"
            git push
          fi
